### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by PattMayne** [penguinite/pothole#2]
I cloned the repo and ran:

> nimble -d:release build --verbose

It failed with the following errors:

```
/home/[USERNAME]/Prog/Nim/pothole/src/pothole/private/apientities.nim(62, 9) template/generic instantiation of `withConnection` from here
/home/[USERNAME]/Prog/Nim/pothole/src/pothole/private/apientities.nim(66, 20) Error: attempting to call undeclared routine: 'getTotalPostsByUserId'
nimble.nim(304)          buildFromDir

    Error:  Build failed for the package: pothole
     Info:  Nimble data file "/home/[USERNAME]/.nimble/nimbledata2.json" has been saved.
```

`db.getTotalPosts() `is also not declared.

When I replace these with hardcoded numbers I'm able to build. But http://localhost:3500/ give an empty "Not Found" page.

**Comment by penguinite** [comment]
The compile-time error is fixed but the page giving a 404 is intentional, pothole is meant to be a backend server, it doesn't really have a frontend of its own. http://127.0.0.1:3500/api/v1/instance works but http://127.0.0.1:3500/ does not.

**Comment by penguinite** [comment]
The README was a bit misleading on what Pothole is and how to use it, sorry for that. I've updated it now.

**Comment by PattMayne** [comment]
Thanks!
